version: '2'
services:
  pertos:
    build: ./deployment/
    container_name: scarf-pertos
    ports:
      - "8090:8080"
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=none
    volumes:
      - "${PWD}/data:/var/lib/neo4j/data"