//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.26 at 04:07:50 PM CET 
//


package org.eclipse.topology.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="pattern" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="arrival" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="behavioral" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="avg_users" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="avg_transactions" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="startTime" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="endTime" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pattern",
    "arrival",
    "behavioral",
    "avgUsers",
    "avgTransactions"
})
@XmlRootElement(name = "Workload")
public class Workload {

    @XmlElement(required = true)
    protected String pattern;
    @XmlElement(required = true)
    protected String arrival;
    @XmlElement(required = true)
    protected String behavioral;
    @XmlElement(name = "avg_users")
    protected short avgUsers;
    @XmlElement(name = "avg_transactions")
    protected short avgTransactions;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "startTime")
    protected String startTime;
    @XmlAttribute(name = "endTime")
    protected String endTime;

    /**
     * Gets the value of the pattern property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPattern() {
        return pattern;
    }

    /**
     * Sets the value of the pattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPattern(String value) {
        this.pattern = value;
    }

    /**
     * Gets the value of the arrival property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArrival() {
        return arrival;
    }

    /**
     * Sets the value of the arrival property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArrival(String value) {
        this.arrival = value;
    }

    /**
     * Gets the value of the behavioral property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBehavioral() {
        return behavioral;
    }

    /**
     * Sets the value of the behavioral property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBehavioral(String value) {
        this.behavioral = value;
    }

    /**
     * Gets the value of the avgUsers property.
     * 
     */
    public short getAvgUsers() {
        return avgUsers;
    }

    /**
     * Sets the value of the avgUsers property.
     * 
     */
    public void setAvgUsers(short value) {
        this.avgUsers = value;
    }

    /**
     * Gets the value of the avgTransactions property.
     * 
     */
    public short getAvgTransactions() {
        return avgTransactions;
    }

    /**
     * Sets the value of the avgTransactions property.
     * 
     */
    public void setAvgTransactions(short value) {
        this.avgTransactions = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the startTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * Sets the value of the startTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartTime(String value) {
        this.startTime = value;
    }

    /**
     * Gets the value of the endTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * Sets the value of the endTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndTime(String value) {
        this.endTime = value;
    }

}
