//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.20 at 10:31:16 PM CET 
//


package org.eclipse.output.TopologyOutput;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.eclipse.topology.domain.MuTopology;
import org.eclipse.toscaModel.TDefinitions;
import org.eclipse.toscaModel.Definitions;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="specification" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Definitions">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;extension base="{http://docs.oasis-open.org/tosca/ns/2011/12}tDefinitions">
 *                           &lt;anyAttribute processContents='lax' namespace='##other'/>
 *                         &lt;/extension>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "viableTopologyWithDababaseID"
})
@XmlRootElement(name = "ViableTopologyList")
public class ViableTopologyList {

    protected List<ViableTopologyList.ViableTopologyWithDababaseID> viableTopologyWithDababaseID;

    /**
     * Gets the value of the specification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the specification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpecification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MuTopologyWithDatabaseId.Specification }
     * 
     * 
     */
    public List<ViableTopologyList.ViableTopologyWithDababaseID> getViableTopologyWithDababaseID() {
        if (viableTopologyWithDababaseID == null) {
        	viableTopologyWithDababaseID = new ArrayList<ViableTopologyList.ViableTopologyWithDababaseID>();
        }
        return this.viableTopologyWithDababaseID;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Definitions">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{http://docs.oasis-open.org/tosca/ns/2011/12}tDefinitions">
     *                 &lt;anyAttribute processContents='lax' namespace='##other'/>
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "databaseId","viableTopology"
    })
    public static class ViableTopologyWithDababaseID {

    	@XmlElement(name = "viableTopology", required = true)
        protected ViableTopologyOutput viableTopology;
        @XmlAttribute(name = "databaseId", required = true)
        protected long databaseId;

        
		public ViableTopologyOutput getViableTopology() {
			return viableTopology;
		}
		public void setViableTopology(ViableTopologyOutput viableTopology) {
			this.viableTopology = viableTopology;
		}
		public long getDatabaseId() {
			return databaseId;
		}
		public void setDatabaseId(long databaseId) {
			this.databaseId = databaseId;
		}
        
		
       
    }

}
